server:
  port: 8072


spring:
  application:
    name: eurekaserver
  config:
    import: "optional:configserver:http://localhost:8889"


management:
  endpoints:
    web:
      exposure:
        include: "*"

  health: # this one related to configure the health indicators
    diskspace:
      threshold: 2MB
    defaults:
      enabled: true
    readinessState:
      enabled: true
    livenessState:
      enabled: true
  endpoint:
    health: # this one related to the endpoint configuration
      probes:
        enabled: true
      show-details: always



eureka:
  instance:
    hostname: localhost

  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
