server:
  port: 0
spring:
  application:
    name: payments
  config:
    import: "configserver:http://localhost:8889"
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh, info, shutdown

#endpoints:
#  shutdown:
#    enabled: true

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.int}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8072/eureka/

info:
  app:
    name: "payments ${server.port}"
    description: "an payment microservice"
    version: 1.0.0