server:
  port: 8082
spring:
  config:
    import: "configserver:http://localhost:8888"
  application:
    name: payments
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh, busrefresh, info, shutdown

#endpoints:
#  shutdown:
#    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "payments"
    description: "an payment microservice"
    version: 1.0.0